# GeeCache 配置文件示例

# 服务器配置
server:
  port: 8001                      # 缓存服务端口
  api_port: 9999                  # API服务端口
  enable_api: false               # 是否启用API服务
  instance_id: ""                 # 实例ID，留空则自动生成
  read_timeout: 10s               # 读取超时
  write_timeout: 10s              # 写入超时
  shutdown_timeout: 30s           # 优雅关闭超时

# 缓存配置
cache:
  strategy: "lru"                 # 缓存策略: lru, lfu, fifo
  max_bytes: 2097152              # 最大缓存字节数 (2MB)
  group_name: "scores"            # 缓存组名称
  replicas: 50                    # 一致性哈希虚拟节点倍数
  peer_timeout: 5s                # 节点间通信超时
  max_idle_conns: 100             # 最大空闲连接数

# 注册中心配置
registry:
  endpoints: # etcd 地址列表
    - localhost:2379
  dial_timeout: 5s                # 连接超时
  username: ""                    # 用户名（可选）
  password: ""                    # 密码（可选）
  service_name: "geeCache"        # 服务名称
  ttl: 10s                        # 服务注册TTL

# 日志配置
log:
  level: "info"                   # 日志级别: debug, info, warn, error
  format: "console"               # 日志格式: json, console
  output_path: "stdout"           # 输出路径: stdout 或文件路径

# 健康检查配置
health:
  enabled: true                   # 是否启用健康检查
  endpoint: "/health"             # 健康检查端点